sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t bbold72/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bbold72/react-test npm run test

# after running tests build production containers
after_success:
  - docker build -t bbold72/multi-client ./client
  - docker build -t bbold72/multi-nginx ./nginx
  - docker build -t bbold72/multi-server ./server
  - docker build -t bbold72/multi-worker ./worker

  # log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # take these images and push to dockerhub
  - docker push -t bbold72/multi-client
  - docker push -t bbold72/multi-nginx
  - docker push -t bbold72/multi-server
  - docker push -t bbold72/multi-worker



