sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t bbold72/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bbold72/react-test npm run test

# after running tests build production containers
after_success:
  - docker build -t bbold72/multi-client ./client
  - docker build -t bbold72/multi-nginx ./nginx
  - docker build -t bbold72/multi-server ./server
  - docker build -t bbold72/multi-worker ./worker

  # log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # take these images and push to dockerhub
  - docker push bbold72/multi-client
  - docker push bbold72/multi-nginx
  - docker push bbold72/multi-server
  - docker push bbold72/multi-worker


deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-633071163946'
  bucket_path: 'multi-docker'
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
